### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/cookie-crud#13]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/cookie-crud`
3. Go to root directory `cd cookie-crud`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by ryuusama09** [comment]
hi@arshadkazmi42  I am a beginner so ill be needing your help .while pushing the updated readme , its showing permission denied . Could you help me out here ?
ps - Ive commited on a separate branch

**Comment by arshadkazmi42** [comment]
@ryuusama09 Sure go ahead. I have assigned the issue to you.

**Comment by ryuusama09** [comment]
> @ryuusama09 Sure go ahead. I have assigned the issue to you.

hi @arshadkazmi42
its showing the following issue : 
<remote: Permission to arshadkazmi42/cookie-crud.git denied to ryuusama09.
fatal: unable to access 'https://github.com/arshadkazmi42/cookie-crud.git/': The requested URL returned error: 403>

**Comment by arshadkazmi42** [comment]
@ryuusama09 You should push in your forked repository. And then create a pull request from your forked repository to https://github.com/arshadkazmi42/cookie-crud.git

If you are new to github, I will highly recommend following this tutorial on how to send a PR. https://github.com/firstcontributions/first-contributions

**Comment by ryuusama09** [comment]
@arshadkazmi42 , Ive done it ,and submitted a pr . Thank you for your cooperation
