### ISSUE TITLE
Remove contributors section from README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/cookie-crud#14]

**Comment by tenocijam** [comment]
Hi! I would like to do this.

**Comment by arshadkazmi42** [comment]
@tenocijam Go ahead.

**Comment by ryuusama09** [comment]
Is this issue still open @arshadkazmi42 ?

**Comment by arshadkazmi42** [comment]
@ryuusama09 There is already a PR created for this. Its pending on me to review. You can explore other issues present in project
