### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/cookie-crud#5]
- Delete package-lock.json
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by nathan-king** [comment]
> * Delete package-lock.json
> * Run `npm install`
> * Commit the updated package-lock.json
> * Create pull request

Hi @arshadkazmi42, I can get this done :)

**Comment by arshadkazmi42** [comment]
@nathan-king sure. go ahead
